services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: er-psscripter-backend
    restart: unless-stopped
    ports:
      - "13021:8000"
    environment:
      - PROJECT_NAME=ER-PSScripter
      - DATABASE_URL=postgresql://user:password@db:5432/erpsscripter
      - BACKEND_CORS_ORIGINS=["http://localhost:13020","http://localhost:5173"]
    volumes:
      - ./backend/data:/app/data
      - /home/dev/Documents:/home/dev/Documents
    depends_on:
      - db
    networks:
      - er-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: er-psscripter-frontend
    restart: unless-stopped
    ports:
      - "13020:80"
    depends_on:
      - backend
    networks:
      - er-network

  db:
    image: pgvector/pgvector:pg15
    container_name: er-psscripter-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=erpsscripter
    networks:
      - er-network

volumes:
  postgres_data:


networks:
  er-network:
    driver: bridge
